name: 'Load Environment Variables'
description: 'Loads environment variables from entity and environment specific files'

inputs:
  entity:
    description: 'The entity name'
    required: true
  environment:
    description: 'The environment name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Source decK environment variables
      shell: bash
      run: |
        echo "::group::Sourcing environment variable files"

        files=(
          "${{ env.ENTITY_COMMON_VARS }}"
          "${{ env.ENTITY_ENV_VARS }}"
          "${{ env.GOVERNANCE_COMMON_VARS }}"
          "${{ env.GOVERNANCE_ENV_VARS }}"
        )

        for file in "${files[@]}"; do
          if [ -f "$file" ]; then
            echo "Sourcing $file"
            set -a
            source "$file"
            set +a
          else
            echo "No environment file found for $file. Skipping."
          fi
        done

        # Export final values of DECK_ variables to GITHUB_ENV
        while IFS='=' read -r key value; do
          if [[ $key == DECK_* ]]; then
            echo "$key=$value" >> "$GITHUB_ENV"
          fi
        done < <(env)

        echo "::endgroup::"
