
# Get APIs
# This workflow is responsible for getting the APIs from the entity's metadata.json file
# It is called by the main build-deploy workflow and runs in parallel for each API defined in the entity's metadata.json file

# Key responsibilities:
# 1. Parses the metadata.json file to extract API configurations
# 2. Filters APIs based on environment-specific settings
# 3. Outputs a list of enabled APIs

# Workflow inputs:
# - entity: The entity (e.g., tripwhiz, roameasy) to get APIs for
# - environment: Target environment (development, acceptance, production)
# - entity_metadata: Path to the entity's metadata.json file

# Main outputs:
# - Generates a list of APIs to be deployed for the given entity and environment


name: Get APIs

on:
  workflow_call:
    inputs:
      entity:
        required: true
        type: string
      environment:
        required: true
        type: string
      entity_metadata:
        required: true
        type: string
    outputs:
      apis:
        description: "List of enabled APIs"
        value: ${{ jobs.get-apis.outputs.apis }}
    secrets:
      KONNECT_TOKEN:
        required: true

jobs:
  get-apis:
    name: Get APIs for ${{ inputs.entity }} ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      apis: ${{ steps.set-apis.outputs.apis }}
    steps:
      - uses: actions/checkout@v4
      - name: Get enabled APIs from metadata
        id: set-apis
        run: |
          APIS=$(jq -c '[ .apis[] | . ]' ${{ inputs.entity_metadata }})
          echo "apis=$APIS" >> $GITHUB_OUTPUT 